nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  sayso-co:
    npmAuthToken: "${NODE_AUTH_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
