name: Publish package
on:
  push:
    tags:
      - 'v*.*.*'   # publish on version tags
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # <-- allows publish with GITHUB_TOKEN
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@your-org'
      - run: npm ci
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
